"""Try a write from a socket-activated service in the sandbox user manager."""

import os
from pathlib import Path
import socket
import subprocess
import sys
import tempfile
import time


def systemctl(*args):
    return subprocess.run(["systemctl", "--user", *args], check=True,
                          text=True, stdout=subprocess.PIPE).stdout.strip()


runtime = Path(os.environ["XDG_RUNTIME_DIR"])
units = runtime / "systemd/user"
units.mkdir(parents=True, exist_ok=True)
with tempfile.TemporaryDirectory(dir=runtime) as directory:
    name = "agentic-job-view-" + Path(directory).name
    endpoint = str(Path(directory) / "socket")
    service = units / (name + ".service")
    trigger = units / (name + ".socket")
    # The probe paths are absolute, generated by the supervisor, and contain
    # no systemd quoting/expansion characters.
    path = sys.argv[1]
    assert all(c.isalnum() or c in "/-_." for c in path)
    # Consume the activation connection, otherwise the listening socket can
    # repeatedly retrigger the service and hide its original exit status.
    code = ('import socket,os; s=socket.socket(fileno=3); c,_=s.accept(); '
            f'c.close(); open("{path}","w").close(); os.unlink("{path}")')
    service.write_text("[Service]\nType=oneshot\nProtectSystem=no\nProtectHome=no\nReadOnlyPaths=\nReadWritePaths=\n"
                       f"ExecStart=/usr/bin/python3 -I -c '{code}'\n")
    trigger.write_text(f"[Socket]\nListenStream={endpoint}\n")
    try:
        systemctl("daemon-reload")
        systemctl("start", trigger.name)
        with socket.socket(socket.AF_UNIX) as client:
            client.connect(endpoint)
        for _ in range(100):
            began = systemctl("show", service.name, "-p", "ExecMainStartTimestampMonotonic", "--value")
            state = systemctl("show", service.name, "-p", "ActiveState", "--value")
            if began != "0" and state in ("inactive", "failed"):
                break
            time.sleep(0.05)
        else:
            raise AssertionError("socket did not activate service")
        result = systemctl("show", service.name, "-p", "ExecMainStatus", "--value")
    finally:
        systemctl("stop", trigger.name, service.name)
        subprocess.run(["systemctl", "--user", "reset-failed", service.name], check=False)
        service.unlink()
        trigger.unlink()
        systemctl("daemon-reload")
    if result == "0":
        sys.exit(0)
    sys.exit(1)
